apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gosra-auto-server-deployment
  name: gosra-auto-server-deployment
  namespace: gosra-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosra-auto-server-deployment
  template:
    metadata:
      labels:
        app: gosra-auto-server-deployment
    spec:
      containers:
        - image: reklaabderrahim/gosra-auto-authentication:latest
          name: gosra-auto-server
---
apiVersion: v1
kind: Service
metadata:
  name: gosra-auto-server-service
  namespace: gosra-auto
spec:
  selector:
    app: gosra-auto-server-deployment
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888