version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9191:80"
    volumes:
      - "pgadmin:/var/lib/pgadmin"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=reklaabderrahim@hotmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=rekla"
  db:
    build:
      context: ../ressources
    container_name: POSTGRES_LOCAL
    volumes:
      - "dbdata-local:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  dbdata-local:
  pgadmin:
